### ISSUE TITLE
p values in netfacs()

### ISSUE THREAD

**Issue by gobbios** [AlexMielke1988/NetFACS#11]
Following up on #10: why do we need two-tailed _p_-values? Usually we are only interested in the right tail, no? And if we implement that, we might omit _z_-values in the first place because as far as I can see their only purpose is to decide later on whether a 'significant' element occurs above or below expected.

**Comment by AlexMielke1988** [comment]
Yes, I think we need two tailed p-values, because elements that are used less in some contexts might still be informative. We can't presuppose what people will use this for. Z-values are really informative as an effect size, and they can give valuable information about the distribution of the random values. For example, if the p-value is significant and the z-value is below 1.96, the underlying null distribution is probably not normally distributed. Many journals will ask users to provide a test statistic, so this is useful.

**Comment by AlexMielke1988** [comment]
The p-right thing was really confusing. I have changed it to have the function parameter 'two.tailed = T', and if it is set to FALSE, people get a one-tailed p value

**Comment by gobbios** [comment]
Alternatively, you could just have two columns with right-tailed and left-tailed.

**Comment by AlexMielke1988** [comment]
people now have the option to choose between two-tailed, right-tailed, or left-tailed. That way, everyone can tailor this to their needs
